#!/usr/bin/env php
<?php

function permissions($dir)
{
	umask(0000);
	if (!is_dir($dir)) {
		@mkdir($dir, 0777, TRUE);

	} else {
		@chmod($dir, 0777);
	}
}

permissions(__DIR__ . '/app/flags');
permissions(__DIR__ . '/app/log');
permissions(__DIR__ . '/app/temp');
permissions(__DIR__ . '/app/temp/sessions');
permissions(__DIR__ . '/app/temp/cache');
permissions(__DIR__ . '/app/data');
permissions(__DIR__ . '/www/public');
permissions(__DIR__ . '/www/cache');
permissions(__DIR__ . '/www/resources');
permissions(__DIR__ . '/app/config');
permissions(__DIR__ . '/app/proxies');

system('curl -s http://getcomposer.org/installer | php');
system('php composer.phar install');
