#!/usr/bin/env php
<?php

function permissions($dir)
{
	system("chmod -R 0777 {$dir}");
}

function isCurlInstalled()
{
	return (bool)system('
			if which curl >/dev/null; then
				echo 1
			else
				echo 0
			fi'
	);
}

permissions(__DIR__ . '/www/public');
permissions(__DIR__ . '/www/cache');
permissions(__DIR__ . '/www/resources');
permissions(__DIR__ . '/app');

if(isCurlInstalled()){
	system('curl -s http://getcomposer.org/installer | php');
}else{
	eval('?>'.file_get_contents('http://getcomposer.org/installer'));
}

system('php composer.phar install');
